"""sabori_csp.core: Low-level bindings for the Sabori CSP constraint solver."""

from sabori_csp._sabori_csp import (
    Domain,
    Variable,
    Model,
    Solver,
    SolverStats,
    Constraint,
    # Comparison constraints
    IntEqConstraint,
    IntNeConstraint,
    IntLtConstraint,
    IntLeConstraint,
    IntMaxConstraint,
    IntMinConstraint,
    IntEqReifConstraint,
    IntNeReifConstraint,
    IntLeReifConstraint,
    IntEqImpConstraint,
    # Arithmetic constraints
    IntTimesConstraint,
    IntAbsConstraint,
    IntModConstraint,
    IntDivConstraint,
    # Linear constraints
    IntLinEqConstraint,
    IntLinLeConstraint,
    IntLinNeConstraint,
    # Reified linear constraints
    IntLinEqReifConstraint,
    IntLinNeReifConstraint,
    IntLinLeReifConstraint,
    IntLinLeImpConstraint,
    # Global constraints
    AllDifferentConstraint,
    AllDifferentGACConstraint,
    AllDifferentExcept0Constraint,
    CircuitConstraint,
    IntElementConstraint,
    IntElementMonotonicConstraint,
    Monotonicity,
    ArrayVarIntElementConstraint,
    ArrayIntMaximumConstraint,
    ArrayIntMinimumConstraint,
    TableConstraint,
    CountEqConstraint,
    CountEqVarTargetConstraint,
    DisjunctiveConstraint,
    DiffnConstraint,
    CumulativeConstraint,
    InverseConstraint,
    RegularConstraint,
    NValueConstraint,
    # Logical constraints
    ArrayBoolAndConstraint,
    ArrayBoolOrConstraint,
    BoolClauseConstraint,
    BoolNotConstraint,
    ArrayBoolXorConstraint,
    BoolXorConstraint,
)

__all__ = [
    "Domain",
    "Variable",
    "Model",
    "Solver",
    "SolverStats",
    "Constraint",
    "IntEqConstraint",
    "IntNeConstraint",
    "IntLtConstraint",
    "IntLeConstraint",
    "IntMaxConstraint",
    "IntMinConstraint",
    "IntEqReifConstraint",
    "IntNeReifConstraint",
    "IntLeReifConstraint",
    "IntEqImpConstraint",
    "IntTimesConstraint",
    "IntAbsConstraint",
    "IntModConstraint",
    "IntDivConstraint",
    "IntLinEqConstraint",
    "IntLinLeConstraint",
    "IntLinNeConstraint",
    "IntLinEqReifConstraint",
    "IntLinNeReifConstraint",
    "IntLinLeReifConstraint",
    "IntLinLeImpConstraint",
    "AllDifferentConstraint",
    "AllDifferentGACConstraint",
    "AllDifferentExcept0Constraint",
    "CircuitConstraint",
    "IntElementConstraint",
    "IntElementMonotonicConstraint",
    "Monotonicity",
    "ArrayVarIntElementConstraint",
    "ArrayIntMaximumConstraint",
    "ArrayIntMinimumConstraint",
    "TableConstraint",
    "CountEqConstraint",
    "CountEqVarTargetConstraint",
    "DisjunctiveConstraint",
    "DiffnConstraint",
    "CumulativeConstraint",
    "InverseConstraint",
    "RegularConstraint",
    "NValueConstraint",
    "ArrayBoolAndConstraint",
    "ArrayBoolOrConstraint",
    "BoolClauseConstraint",
    "BoolNotConstraint",
    "ArrayBoolXorConstraint",
    "BoolXorConstraint",
]
